const locals = {
    SigningIn: "Signing in...",
    Logout: "Logout",
    SignIn: "Sign In",
    SignUp: "Sign Up",
    Username: "Username",
    Password: "Password",
    EnterUsername: "Enter your username",
    EnterPassword: "Enter your password",
    Login: "Login",
    Register: "Register",
    ForgotPassword: "Forgot Password?",
    RememberMe: "Remember Me",
    LoginSuccess: "Login successful!",
    LoginFailed: "Login failed. Please check your credentials.",
    RegisterSuccess: "Registration successful! Please log in.",
    FetchError: "Error fetching data. Please try again later.",
    Unauthorized: "You are not authorized to view this page.",
    NotFound: "Page not found.",
    ServerError: "Internal server error. Please try again later.",
    NetworkError: "Network error. Please check your connection.",

    // Dashboard
    Dashboard: "Dashboard",
    TotalEmployees: "Total Employees",
    TotalSuppliers: "Total Suppliers",
    TodaysTrips: "Today's Trips",
    TodaysAttendance: "Today's Attendance",
    QuickActions: "Quick Actions",
    ScheduleTrip: "Schedule Trip",
    RecordBoughtLeaf: "Record Bought Leaf",
    ViewAttendance: "View Attendance",

    // User Management
    AddEmployee: "Add Employee",
    AddSupplier: "Add Supplier",
    EditEmployee: "Edit Employee",
    EditSupplier: "Edit Supplier",
    EmployeeDetails: "Employee Details",
    SupplierDetails: "Supplier Details",
    Name: "Name",
    NicNumber: "NIC Number",
    Birthday: "Birthday",
    PhotoUrl: "Photo URL",
    NicUrl: "NIC URL",
    Job: "Job",
    JobTitle: "Job Title",
    CustomId: "Custom ID",
    RouteId: "Route",
    CreatedSuccess: "Created successfully!",
    UpdatedSuccess: "Updated successfully!",
    DeletedSuccess: "Deleted successfully!",
    CreateError: "Error creating record. Please try again.",
    UpdateError: "Error updating record. Please try again.",
    DeleteError: "Error deleting record. Please try again.",

    // Bank Details
    BankDetails: "Bank Details",
    AddBankDetails: "Add Bank Details",
    Bank: "Bank",
    AccountNumber: "Account Number",
    Branch: "Branch",
    NameInAccount: "Name in Account",
    NoBankDetails: "No bank details found for this user.",

    // Fleet Management
    LorryManagement: "Lorry Management",
    LorryManagementDesc: "Manage your fleet of lorries and their mileage records.",
    AddLorry: "Add Lorry",
    EditLorry: "Edit Lorry",
    LorryNumber: "Lorry Number",
    Mileage: "Mileage",
    RouteManagement: "Route Management",
    RouteManagementDesc: "Manage collection routes and their line names.",
    AddRoute: "Add Route",
    LineName: "Line Name",
    ConfirmDelete: "Are you sure you want to delete this item?",

    // Trip Management
    TripManagement: "Trip Management",
    TripManagementDesc: "View and manage scheduled trips.",
    StartMileage: "Start Mileage",
    EndMileage: "End Mileage",
    TripCreatedSuccess: "Trip created successfully!",
    TripCreateError: "Error creating trip. Please try again.",

    // Attendance
    DailyAttendance: "Daily Attendance",
    DailyAttendanceDesc: "View and manage employee attendance records for the day.",
    CheckInOut: "Check In/Out",
    CheckInOutSuccess: "Attendance recorded successfully!",
    CheckInOutError: "Error recording attendance. Please try again.",
    Date: "Date",

    // Bought Leaf
    BoughtLeafSummary: "Bought Leaf - Daily Summary",
    BoughtLeafSummaryDesc: "View daily bought leaf collection summary across all suppliers.",
    RecordBoughtLeafEntry: "Record Bought Leaf Entry",
    RecordBoughtLeafDesc: "Record a new bought leaf collection entry for a supplier.",
    Supplier: "Supplier",
    Weight: "Weight (kg)",
    WaterDeduction: "Water Deduction (kg)",
    TareDeduction: "Tare Deduction (kg)",
    NetWeight: "Net Weight (kg)",
    BoughtLeafCreatedSuccess: "Bought leaf entry recorded successfully!",
    BoughtLeafCreateError: "Error recording bought leaf entry. Please try again.",

    // Common
    Save: "Save",
    Cancel: "Cancel",
    Close: "Close",
    Create: "Create",
    Edit: "Edit",
    Delete: "Delete",
    View: "View",
    Loading: "Loading...",
    NoDataFound: "No data found.",
    Actions: "Actions",
    Refresh: "Refresh",
};

export default locals;